### PR TITLE
Add a LICENSE file

### PR DESCRIPTION
**Pull request by sudoforge**
```
Add a LICENSE file

This commit adds a LICENSE file, which is helpful to users in
environments which require a license for compliance reasons.
```

---

I chose an MIT license as that is most common in the open source world, however, if this is not what you desire, please let me know.

### CODE REVIEW

**Comment by sudoforge** [comment]
Closing; a license was added in be4de3ded2031f90563be067b646175184cfe7d5.

Thanks @benknoble!

**Comment by benknoble** [comment]
I've added a license, so this is closed.

Please consider deleting your branch with an invalid license; as it stands, prior to my license being available, you didn't have the right to modify the code in any way (including licensing it). Worse, no one ever has the right to license someone else's work in their name. I don't want someone to see your branch and get confused about the state of affairs.

(P.S. Thanks for calling attention to the missing license. I want my projects to be freely shared and improved!)

**Comment by sudoforge** [comment]
> Please consider deleting your branch with an invalid license

I always delete my forks of projects I'm contributing ad-hoc to after the tree is merged or rejected, not to worry!

**Comment by benknoble** [comment]
No worries; I only want to make sure that (a) a potentially unfortunate legal situation you created for yourself is resolved and (b) that future newcomers aren't confused by the licensing issues/options.

Of course, _now_ that I have provided a very liberal license, you _may_ re-license the source at will under the terms of that particular license _as long as_ you abide by the requirements (see the license for details). But the issue was the timeline: you re-licensed my work when you had no right to do so; now you do. The former situation was illegal (though I obviously won't pursue the matter as the offending license is effectively gone) and may have confused newcomers. Just keep that in mind.

**Comment by sudoforge** [comment]
You are misunderstanding the rights you have with code that you have published to GitHub in a public repository. By forking your code and adding a license, I was in no way "creating a potentially unfortunate legal situation for myself", nor did I have "no right" to "re-license your work".

What follows are excerpts from [GitHub's Terms of Service](https://docs.github.com/en/github/site-policy/github-terms-of-service#5-license-grant-to-other-users) as of Friday, 12 Nov 2021 15:01:29 GMT.

**[Ownership of Content, Right to Post, and License Grants](https://docs.github.com/en/github/site-policy/github-terms-of-service#3-ownership-of-content-right-to-post-and-license-grants)**

> You retain ownership of and responsibility for Your Content. If you're posting anything you did not create yourself or do not own the rights to, you agree that you are responsible for any Content you post; that you will only submit Content that you have the right to post; and that you will fully comply with any third party licenses relating to Content you post.
> 
> Because you retain ownership of and responsibility for Your Content, we need you to grant us — and other GitHub Users — certain legal permissions, listed in Sections D.4 — D.7. These license grants apply to Your Content. If you upload Content that already comes with a license granting GitHub the permissions we need to run our Service, no additional license is required. You understand that you will not receive any payment for any of the rights granted in Sections D.4 — D.7. The licenses you grant to us will end when you remove Your Content from our servers, unless other Users have forked it.

**[License Grant to Other Users](https://docs.github.com/en/github/site-policy/github-terms-of-service#5-license-grant-to-other-users)**

> Any User-Generated Content you post publicly, including issues, comments, and contributions to other Users' repositories, may be viewed by others. By setting your repositories to be viewed publicly, you agree to allow others to view and "fork" your repositories (this means that others may make their own copies of Content from your repositories in repositories they control).
>
> If you set your pages and repositories to be viewed publicly, you grant each User of GitHub a nonexclusive, worldwide license to use, display, and perform Your Content through the GitHub Service and to reproduce Your Content solely on GitHub as permitted through GitHub's functionality (for example, through forking). You may grant further rights if you [adopt a license](https://docs.github.com/en/articles/adding-a-license-to-a-repository/#including-an-open-source-license-in-your-repository). If you are uploading Content you did not create or own, you are responsible for ensuring that the Content you upload is licensed under terms that grant these permissions to other GitHub Users.

---

With my nonexclusive, worldwide license to use, display, and perform your repository (aka "Your Content"; see the definitions of terms on the linked pages), I decided to add a `LICENSE` file, containing an open source license attributed to you, and then suggest this change from my copy of Your Content, back to you. These actions were performed through the GitHub Service.

I am not a lawyer, nor are you, however, you are free to consult one if you wish to gain further understanding of what content you post publicly on GitHub is subject to.

**Comment by benknoble** [comment]
Again, I want to be friendly here, and for my work to be shareable, useable, etc.

Your right to "use, display, and perform", to "reproduce […] solely on GitHub" or to "fork" still does not grant you the right to modify or license. I'm not sure there's any more to it, unless there are other relevant parts of sections D1–D4 that you haven't quoted.

My end goal was not to chastise, harass, or prosecute you, but simply to point out an illegal situation that you may find unpleasant and a confusing situation which I would like to address.  

Thank you though for pointing out that there is an (implicit) set of terms that I grant by publicizing the code on GitHub. I was unaware of such an agreement, though it makes sense.

Anyway, I think this is all moot, since your copy no longer exists, no? If that's the case, I'll simply refrain from commenting here further unless need arises.

**Comment by benknoble** [comment]
> You are misunderstanding the rights you have with code that you have published to GitHub in a public repository.

P.S. It is not my rights that are the (misunderstood) issue, but rather those I granted or had yet to grant to others. Again, I thank you for pointing out that there were rights granted I was unaware of, but prior to my licensing the code under a permissive license I had still not yet granted the rights to modify or license.

**Comment by sudoforge** [comment]
Without specifying a license, I can fork your project and do whatever I want to my copy, as long as that is done through GitHub.

Again, I recommend you consult a lawyer before attempting to definitively state what is and is not permissible with public source code that you publish on GitHub. Forking and contributing is well within my rights, or the rights of any other GitHub user, per GitHub's Terms of Service.

**Comment by benknoble** [comment]
*sigh* back again.

> Forking and contributing is well within my rights, or the rights of any other GitHub user, per GitHub's Terms of Service.

I didn't read "contributing" in the rights you quoted, but I won't argue about that, since I welcome contributions. I'm going to examine modifications and licensing, since filing issues, etc., is also contributing but not relevant here.

> Without specifying a license, I can fork your project and do whatever I want to my copy, as long as that is done through GitHub.

This is only partially correct, if I understand the way licensing works.

Let's say I have a piece of software. Without granting any licenses, I retain all rights to it, and no one else has any. Agreed?

Let's say I then publish the (otherwise unlicensed) code on GitHub publicly. I (implicitly) agree to the terms GitHub sets forth and grant the license you quoted. That is, you (along with all other GitHub users), are granted the rights set out below:

> Any User-Generated Content you post publicly, including issues, comments, and contributions to other Users' repositories, may be viewed by others. By setting your repositories to be viewed publicly, you agree to allow others to view and "fork" your repositories (this means that others may make their own copies of Content from your repositories in repositories they control).

> If you set your pages and repositories to be viewed publicly, you grant each User of GitHub a nonexclusive, worldwide license to use, display, and perform Your Content through the GitHub Service and to reproduce Your Content solely on GitHub as permitted through GitHub's functionality (for example, through forking). You may grant further rights if you adopt a license. If you are uploading Content you did not create or own, you are responsible for ensuring that the Content you upload is licensed under terms that grant these permissions to other GitHub Users.

You may, under those terms,
- view my content,
- make a copy ("fork"), which you did under the license granted,
- use, display, and perform my content through the GitHub Service,
- reproduce my content solely on GitHub as permitted by GitHub's functionality.

Agreed?

Notice that "control" in the above quotes, as referring to forks, is about your control of the repository, not the Content. You do not "own" the Content. Another of your quotes explicitly said that I retain control, since I created it.

I retain all other rights, as no others have been granted. Agreed?

The rights I retain include the right to modify, as well as the copyright. Since I own the copyright, I can grant licenses of rights. You cannot; you have been granted no right to, nor do you have ownership over the copyright. Agreed?

Now, I add a license that allows these things. Only then may you legally choose to act within the rights of the license, effectively accepting its terms and conditions. If multiple licenses exist, you may choose to act under any and all of them (so long as they are not exclusive, I think) as long as you abide by the terms and conditions of each license whose rights you exercise. Agreed?

---

I'm really not sure where you leapt from thinking that because the code is public you have certain rights as spelled out, to thinking that you can do "do whatever [you] want to [your] copy." You may do only that which has been granted as a right, and I have established a hypothetical timeline along with exactly what rights are allowed when.

So it seems to me that you misunderstand what rights are granted to GitHub users on public but otherwise unlicensed code. Without a license, you have no agreement with the owner about what you may do with their content, and thus no rights to do anything. GitHub requires me to automatically grant a certain license when such code is public. That is still the only agreement you have delimiting what you may do. And, I repeat, the specific license required by GitHub does not grant you rights to do whatever you want, nor does it grant you the right to modify, nor re-license.

If you can point me to GitHub terms that say otherwise, I will read them and reconsider or retract my statements.

But to summarize: free public otherwise-unlicensed code _is not public domain_, and _does not come with the right to do whatever you want with it_. Whether or not it should is a different question. 

---

If I make a piece of music, share it, and say "anyone can download and listen to it," I still have not granted permission to modify that music, nor include it in their music, nor sell it, nor grant other rights to others on it (aka license it). This is not so different from where we are here, in my eyes, and also not so controversial…

But honestly, I cannot continue this conversation. So, unless you have terms to direct me to as I mentioned, I will no longer reply to this thread. I will, however, not close it, in case you do indeed reply with said terms.

**Comment by sudoforge** [comment]
I'll end with this:

Unlike you, I am not spouting my own interpretation of GitHub's intentionally vague Terms of Service. Instead, I am summarizing a conversation with an attorney. For the third time, I would encourage you to consult a lawyer before attempting to definitively state what users can and cannot do with public source code you publish to GitHub.

**Pull request closed without merging**
